// Chinese zodiac dataset — ported from astral-day (emojis stripped; we draw sigils instead).

export interface ChineseZodiacSign {
  key: string;
  name: string;
  element: string;
  years: number[];
  traits: string[];
  strengths: string[];
  weaknesses: string[];
  compatibility: { best: string[]; good: string[]; bad: string[] };
  celebrities: string[];
  description: string;
  luckyNumbers: number[];
  luckyColors: string[];
  luckyDirections: string[];
}

export const CHINESE_ZODIAC_SIGNS: ChineseZodiacSign[] = [] = [
  {
    key: 'rat',
    name: 'Rat',
    element: 'Water',
    years: [1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032],
    traits: ['Quick-witted', 'Resourceful', 'Versatile', 'Smart', 'Curious'],
    strengths: [
      'Quick thinking and adaptability',
      'Excellent memory and observation skills',
      'Natural leadership abilities',
      'Strong survival instincts',
      'Charming and sociable personality',
    ],
    weaknesses: [
      'Can be overly critical',
      'Sometimes too ambitious',
      'May lack patience',
      'Can be opportunistic',
      'Tendency to be materialistic',
    ],
    compatibility: {
      best: ['dragon', 'monkey'],
      good: [
        'ox',
        'tiger',
        'rabbit',
        'snake',
        'horse',
        'goat',
        'rooster',
        'dog',
        'pig',
      ],
      bad: ['horse'],
    },
    celebrities: [
      'Shakespeare (1564)',
      'George Washington (1732)',
      'Prince Harry (1984)',
      'Scarlett Johansson (1984)',
      'Eminem (1972)',
      'Cameron Diaz (1972)',
    ],
    description:
      'The Rat is the first sign in the Chinese zodiac cycle. People born in the Year of the Rat are known for their quick wit, resourcefulness, and adaptability. They are natural leaders with excellent memory and observation skills, making them successful in various fields.',
    luckyNumbers: [2, 3],
    luckyColors: ['Gold', 'Blue', 'Green'],
    luckyDirections: ['Northeast', 'Northwest'],
  },
  {
    key: 'ox',
    name: 'Ox',
    element: 'Earth',
    years: [1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021, 2033],
    traits: ['Diligent', 'Dependable', 'Determined', 'Patient', 'Honest'],
    strengths: [
      'Strong work ethic and reliability',
      'Excellent organizational skills',
      'Natural leadership through example',
      'Patient and methodical approach',
      'Loyal and trustworthy nature',
    ],
    weaknesses: [
      'Can be stubborn and inflexible',
      'Sometimes too traditional',
      'May lack communication skills',
      'Can be overly serious',
      'Difficulty expressing emotions',
    ],
    compatibility: {
      best: ['rat', 'snake', 'rooster'],
      good: [
        'tiger',
        'rabbit',
        'dragon',
        'horse',
        'goat',
        'monkey',
        'dog',
        'pig',
      ],
      bad: ['goat'],
    },
    celebrities: [
      'Napoleon Bonaparte (1769)',
      'Vincent van Gogh (1853)',
      'Barack Obama (1961)',
      'Sandra Bullock (1964)',
      'George Clooney (1961)',
      'Kate Winslet (1975)',
    ],
    description:
      'The Ox represents hard work, reliability, and determination. People born in the Year of the Ox are known for their strong work ethic, patience, and methodical approach to life. They are natural leaders who lead by example and are highly respected for their integrity.',
    luckyNumbers: [1, 4],
    luckyColors: ['White', 'Yellow', 'Green'],
    luckyDirections: ['North', 'South'],
  },
  {
    key: 'tiger',
    name: 'Tiger',
    element: 'Wood',
    years: [1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034],
    traits: ['Brave', 'Competitive', 'Confident', 'Charismatic', 'Independent'],
    strengths: [
      'Natural leadership and charisma',
      'Courage and bravery in challenges',
      'Strong competitive spirit',
      'Independent and self-reliant',
      'Passionate and energetic nature',
    ],
    weaknesses: [
      'Can be impulsive and reckless',
      'Sometimes too aggressive',
      'May lack patience',
      'Can be overly competitive',
      'Difficulty with authority',
    ],
    compatibility: {
      best: ['horse', 'dog'],
      good: [
        'rat',
        'ox',
        'rabbit',
        'dragon',
        'snake',
        'goat',
        'monkey',
        'rooster',
        'pig',
      ],
      bad: ['monkey'],
    },
    celebrities: [
      'Queen Elizabeth II (1926)',
      'Marilyn Monroe (1926)',
      'Leonardo DiCaprio (1974)',
      'Lady Gaga (1986)',
      'Tom Hardy (1977)',
      'Emma Stone (1988)',
    ],
    description:
      'The Tiger symbolizes courage, strength, and leadership. People born in the Year of the Tiger are natural leaders with magnetic personalities. They are brave, competitive, and independent, often taking on challenges that others might avoid.',
    luckyNumbers: [1, 3, 4],
    luckyColors: ['Orange', 'Gray', 'Blue'],
    luckyDirections: ['East', 'South'],
  },
  {
    key: 'rabbit',
    name: 'Rabbit',
    element: 'Wood',
    years: [1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035],
    traits: ['Quiet', 'Elegant', 'Kind', 'Patient', 'Diplomatic'],
    strengths: [
      'Excellent diplomatic skills',
      'Natural elegance and grace',
      'Strong intuition and empathy',
      'Patient and thoughtful approach',
      'Good taste and aesthetic sense',
    ],
    weaknesses: [
      'Can be overly cautious',
      'Sometimes too passive',
      'May avoid confrontation',
      'Can be moody',
      'Difficulty making quick decisions',
    ],
    compatibility: {
      best: ['goat', 'pig'],
      good: [
        'rat',
        'ox',
        'tiger',
        'dragon',
        'snake',
        'horse',
        'monkey',
        'rooster',
        'dog',
      ],
      bad: ['rooster'],
    },
    celebrities: [
      'Albert Einstein (1879)',
      'Frank Sinatra (1915)',
      'Johnny Depp (1963)',
      'Angelina Jolie (1975)',
      'Brad Pitt (1963)',
      'Emma Watson (1990)',
    ],
    description:
      'The Rabbit represents grace, elegance, and diplomacy. People born in the Year of the Rabbit are known for their gentle nature, excellent taste, and diplomatic skills. They are patient, thoughtful, and have a natural sense of beauty and harmony.',
    luckyNumbers: [3, 4, 6],
    luckyColors: ['Red', 'Pink', 'Purple', 'Blue'],
    luckyDirections: ['East', 'South', 'North'],
  },
  {
    key: 'dragon',
    name: 'Dragon',
    element: 'Fire',
    years: [1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024, 2036],
    traits: ['Confident', 'Intelligent', 'Enthusiastic', 'Lucky', 'Powerful'],
    strengths: [
      'Natural charisma and leadership',
      'Strong willpower and determination',
      'Lucky and fortunate in life',
      'Intelligent and quick-witted',
      'Passionate and enthusiastic nature',
    ],
    weaknesses: [
      'Can be arrogant and overconfident',
      'Sometimes too impulsive',
      'May be impatient',
      'Can be demanding',
      'Difficulty with criticism',
    ],
    compatibility: {
      best: ['rat', 'monkey', 'rooster'],
      good: ['ox', 'tiger', 'rabbit', 'snake', 'horse', 'goat', 'dog', 'pig'],
      bad: ['dog'],
    },
    celebrities: [
      'Bruce Lee (1940)',
      'John Lennon (1940)',
      'Sandra Bullock (1964)',
      'Reese Witherspoon (1976)',
      'Christian Bale (1974)',
      'Emma Stone (1988)',
    ],
    description:
      'The Dragon is the most powerful and lucky sign in Chinese astrology. People born in the Year of the Dragon are natural leaders with magnetic personalities. They are confident, intelligent, and often achieve great success in their chosen fields.',
    luckyNumbers: [1, 6, 7],
    luckyColors: ['Gold', 'Silver', 'Gray'],
    luckyDirections: ['East', 'South', 'North'],
  },
  {
    key: 'snake',
    name: 'Snake',
    element: 'Fire',
    years: [1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025, 2037],
    traits: ['Enigmatic', 'Intelligent', 'Wise', 'Mysterious', 'Intuitive'],
    strengths: [
      'Deep wisdom and intuition',
      'Excellent analytical skills',
      'Mysterious and enigmatic nature',
      'Strong determination and focus',
      'Natural healing abilities',
    ],
    weaknesses: [
      'Can be secretive and distrustful',
      'Sometimes too possessive',
      'May be jealous',
      'Can be vengeful',
      'Difficulty expressing emotions',
    ],
    compatibility: {
      best: ['ox', 'rooster'],
      good: [
        'rat',
        'tiger',
        'rabbit',
        'dragon',
        'horse',
        'goat',
        'monkey',
        'dog',
        'pig',
      ],
      bad: ['pig'],
    },
    celebrities: [
      'Mahatma Gandhi (1869)',
      'Bob Dylan (1941)',
      'Brad Pitt (1963)',
      'Orlando Bloom (1977)',
      'Taylor Swift (1989)',
      'Daniel Radcliffe (1989)',
    ],
    description:
      'The Snake represents wisdom, intuition, and mystery. People born in the Year of the Snake are deep thinkers with excellent analytical skills. They are intuitive, wise, and often have a mysterious aura that draws others to them.',
    luckyNumbers: [2, 8, 9],
    luckyColors: ['Black', 'Red', 'Dark Brown'],
    luckyDirections: ['West', 'Northwest', 'Southwest'],
  },
  {
    key: 'horse',
    name: 'Horse',
    element: 'Fire',
    years: [1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026, 2038],
    traits: ['Animated', 'Active', 'Energetic', 'Adventurous', 'Free-spirited'],
    strengths: [
      'Natural energy and enthusiasm',
      'Adventurous and free-spirited nature',
      'Strong communication skills',
      'Quick thinking and adaptability',
      'Natural leadership abilities',
    ],
    weaknesses: [
      'Can be impatient and impulsive',
      'Sometimes too independent',
      'May lack patience',
      'Can be stubborn',
      'Difficulty with routine',
    ],
    compatibility: {
      best: ['tiger', 'goat'],
      good: [
        'rat',
        'ox',
        'rabbit',
        'dragon',
        'snake',
        'monkey',
        'rooster',
        'dog',
        'pig',
      ],
      bad: ['rat'],
    },
    celebrities: [
      'John Wayne (1907)',
      'Paul McCartney (1942)',
      'Jackie Chan (1954)',
      'Katy Perry (1984)',
      'Kristen Stewart (1990)',
      'Robert Pattinson (1986)',
    ],
    description:
      'The Horse symbolizes energy, freedom, and adventure. People born in the Year of the Horse are energetic, enthusiastic, and love freedom. They are natural communicators with a strong sense of adventure and independence.',
    luckyNumbers: [2, 3, 7],
    luckyColors: ['Green', 'Yellow', 'Orange'],
    luckyDirections: ['South', 'East'],
  },
  {
    key: 'goat',
    name: 'Goat',
    element: 'Earth',
    years: [1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027, 2039],
    traits: ['Calm', 'Gentle', 'Sympathetic', 'Artistic', 'Peaceful'],
    strengths: [
      'Natural artistic and creative abilities',
      'Gentle and compassionate nature',
      'Strong sense of harmony and peace',
      'Excellent taste and aesthetic sense',
      'Loyal and caring personality',
    ],
    weaknesses: [
      'Can be indecisive and insecure',
      'Sometimes too dependent',
      'May avoid confrontation',
      'Can be pessimistic',
      'Difficulty with change',
    ],
    compatibility: {
      best: ['rabbit', 'horse', 'pig'],
      good: [
        'rat',
        'ox',
        'tiger',
        'dragon',
        'snake',
        'monkey',
        'rooster',
        'dog',
      ],
      bad: ['ox'],
    },
    celebrities: [
      'Julia Roberts (1967)',
      'Nicole Kidman (1967)',
      'Mel Gibson (1956)',
      'Meryl Streep (1949)',
      'Bruce Willis (1955)',
      'Kate Middleton (1982)',
    ],
    description:
      'The Goat represents peace, harmony, and creativity. People born in the Year of the Goat are gentle, artistic, and have a natural sense of beauty. They are compassionate and caring, often putting others before themselves.',
    luckyNumbers: [2, 7],
    luckyColors: ['Green', 'Purple', 'Brown'],
    luckyDirections: ['South', 'North'],
  },
  {
    key: 'monkey',
    name: 'Monkey',
    element: 'Metal',
    years: [1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028, 2040],
    traits: ['Sharp', 'Smart', 'Curious', 'Innovative', 'Versatile'],
    strengths: [
      'Quick wit and intelligence',
      'Innovative and creative thinking',
      'Excellent problem-solving skills',
      'Adaptable and versatile nature',
      'Natural curiosity and learning ability',
    ],
    weaknesses: [
      'Can be restless and impatient',
      'Sometimes too clever for their own good',
      'May lack consistency',
      'Can be mischievous',
      'Difficulty with routine tasks',
    ],
    compatibility: {
      best: ['rat', 'dragon'],
      good: [
        'ox',
        'tiger',
        'rabbit',
        'snake',
        'horse',
        'goat',
        'rooster',
        'dog',
        'pig',
      ],
      bad: ['tiger'],
    },
    celebrities: [
      'Elizabeth Taylor (1932)',
      'Tom Hanks (1956)',
      'Will Smith (1968)',
      'Leonardo DiCaprio (1974)',
      'Justin Timberlake (1981)',
      'Emma Watson (1990)',
    ],
    description:
      'The Monkey represents intelligence, innovation, and versatility. People born in the Year of the Monkey are quick-witted, creative, and excellent problem-solvers. They are curious, adaptable, and often excel in technical or innovative fields.',
    luckyNumbers: [4, 9],
    luckyColors: ['White', 'Blue', 'Gold'],
    luckyDirections: ['North', 'Northwest'],
  },
  {
    key: 'rooster',
    name: 'Rooster',
    element: 'Metal',
    years: [1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029, 2041],
    traits: ['Observant', 'Hardworking', 'Courageous', 'Talented', 'Confident'],
    strengths: [
      'Strong work ethic and determination',
      'Excellent observation skills',
      'Natural talent and creativity',
      'Courageous and confident nature',
      'Reliable and trustworthy personality',
    ],
    weaknesses: [
      'Can be overly critical',
      'Sometimes too perfectionist',
      'May be boastful',
      'Can be impatient',
      'Difficulty with criticism',
    ],
    compatibility: {
      best: ['ox', 'snake'],
      good: [
        'rat',
        'tiger',
        'rabbit',
        'dragon',
        'horse',
        'goat',
        'monkey',
        'dog',
        'pig',
      ],
      bad: ['rabbit'],
    },
    celebrities: [
      'Elvis Presley (1935)',
      'Roger Federer (1981)',
      'Jennifer Lawrence (1990)',
      'Adele (1988)',
      'Beyoncé (1981)',
      'Ryan Reynolds (1976)',
    ],
    description:
      'The Rooster represents confidence, talent, and hard work. People born in the Year of the Rooster are observant, hardworking, and naturally talented. They are confident, courageous, and often excel in creative or performance fields.',
    luckyNumbers: [5, 7, 8],
    luckyColors: ['Gold', 'Brown', 'Yellow'],
    luckyDirections: ['South', 'Southeast'],
  },
  {
    key: 'dog',
    name: 'Dog',
    element: 'Earth',
    years: [1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030, 2042],
    traits: ['Loyal', 'Honest', 'Friendly', 'Responsible', 'Protective'],
    strengths: [
      'Loyalty and devotion to others',
      'Honest and trustworthy nature',
      'Strong sense of justice',
      'Protective and caring personality',
      'Reliable and responsible behavior',
    ],
    weaknesses: [
      'Can be stubborn and opinionated',
      'Sometimes too critical',
      'May be pessimistic',
      'Can be overly protective',
      'Difficulty with change',
    ],
    compatibility: {
      best: ['tiger', 'horse'],
      good: [
        'rat',
        'ox',
        'rabbit',
        'dragon',
        'snake',
        'goat',
        'monkey',
        'rooster',
        'pig',
      ],
      bad: ['dragon'],
    },
    celebrities: [
      'Winston Churchill (1874)',
      'Madonna (1958)',
      'Sylvester Stallone (1946)',
      'Michael Jackson (1958)',
      'Justin Bieber (1994)',
      'Lady Gaga (1986)',
    ],
    description:
      'The Dog represents loyalty, honesty, and friendship. People born in the Year of the Dog are loyal, honest, and have a strong sense of justice. They are protective, caring, and often put others before themselves.',
    luckyNumbers: [3, 4, 9],
    luckyColors: ['Red', 'Green'],
    luckyDirections: ['East', 'South'],
  },
  {
    key: 'pig',
    name: 'Pig',
    element: 'Water',
    years: [1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031, 2043],
    traits: ['Compassionate', 'Generous', 'Diligent', 'Honest', 'Optimistic'],
    strengths: [
      'Compassionate and generous nature',
      'Strong work ethic and determination',
      'Honest and trustworthy personality',
      'Optimistic and positive outlook',
      'Natural peacemaking abilities',
    ],
    weaknesses: [
      'Can be naive and trusting',
      'Sometimes too generous',
      'May be stubborn',
      'Can be materialistic',
      'Difficulty with criticism',
    ],
    compatibility: {
      best: ['rabbit', 'goat'],
      good: [
        'rat',
        'ox',
        'tiger',
        'dragon',
        'snake',
        'horse',
        'monkey',
        'rooster',
        'dog',
      ],
      bad: ['snake'],
    },
    celebrities: [
      'Ernest Hemingway (1899)',
      'Ronald Reagan (1911)',
      'Arnold Schwarzenegger (1947)',
      'Hilary Swank (1974)',
      'Eminem (1972)',
      'Justin Timberlake (1981)',
    ],
    description:
      'The Pig represents compassion, generosity, and diligence. People born in the Year of the Pig are kind, generous, and have a strong work ethic. They are honest, optimistic, and often bring peace and harmony to their relationships.',
    luckyNumbers: [2, 5, 8],
    luckyColors: ['Yellow', 'Gray', 'Brown', 'Gold'],
    luckyDirections: ['North', 'Northeast', 'Southwest'],
  },
];

export function getChineseZodiacSign(key: string): ChineseZodiacSign | undefined {
  return CHINESE_ZODIAC_SIGNS.find((s) => s.key === key);
}
